---
#ログインメッセージの出力先を指定します。
# -1 => 出力を変更しない
# 0 => 出力しない
# 1 => 通常(チャットメッセージ)
# 2 => 画面中央付近
# 3 => アイテムスロットの上
Join_Message_destination: 1


#ログアウトメッセージの出力先を指定します。
# -1 => 出力を変更しない
# 0 => 出力しない
# 1 => 通常(チャットメッセージ)
# 2 => 画面中央付近
# 3 => アイテムスロットの上
Quit_Message_destination: 1

#ログインメッセージをコンソールに出力するかどうかを指定します。
#この設定はメッセージの出力先をチャットメッセージに設定した際に、コンソールにログインメッセージは2重出力を抑制するものです。
# yes => 出力する
# no => 出力しない
console_output: yes

#ログイン時に出力するメッセージを指定します。
#複数指定した場合は、ランダムに出力されます。
# 「#PLAYER」 はプレーヤーネームに置換されます。
JoinMessages:
- '#PLAYER がゲームに参加しました'

#ログアウト時に出力するメッセージを指定します。
#複数指定した場合は、ランダムに出力されます。
# 「#PLAYER」 はプレーヤーネームに置換されます。
QuitMessages:
- '#PLAYER がゲームを退出しました'
...
